--- # jekyll config
title: abundance w/ Gradual Change
url: abundance.netligy.com
defaults:
 - scope:
    path: ""
    type: pages
   values:
    layout: default

exclude:
 - publish.sh
 - _site
 - Gemfile
 - Gemfile.lock
 - travis.sh
 - "*.org"
 - "*.mpeg"
 - "*.mp4"
 - "*.mp3"

